- hosts: docker
  tasks:
     - name: installing the httpd service
       package:
               name: "httpd"
               state: present

     - name: creating the html file
       copy:
               src: "/etc/ansible/2021.html"
               dest: "/var/www/html/"

     - name: starting httpd service
       command: /usr/sbin/httpd


